"""Apply a reviewed copy plan: original's properties onto the second PDF's content.

Inputs are the comparison rows (what exists where), the plan (the action the
user chose for each row: copy / keep / remove / custom value) and the output
options (document-wide decisions such as annotations, encryption, version).
The second PDF is opened, modified in memory and saved to a *new* file;
neither upload is ever written to.

Every row produces a report item whose outcome is one of :data:`OUTCOMES`.
"""

from __future__ import annotations

import json
import re
import secrets
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import pikepdf
from pikepdf import Array, Dictionary, Name, Pdf, Stream, String

from dittopdf.services import headerfix, numbering, pdfobj, pdfwriter, rawfile, resources, xmp
from dittopdf.services.model import (
    COPY, CUSTOM, DIRECT, KEEP, READONLY, RECONSTRUCT, REGENERATE, REMOVE, UNREPRODUCIBLE,
)
from dittopdf.services.pdfobj import is_obj
from dittopdf.services.transplant import Transplanter

OUTCOMES = {
    "copied": "Successfully copied",
    "reconstructed": "Reconstructed",
    "overridden": "Manual override applied",
    "removed": "Removed (to match the original or as chosen)",
    "kept": "Kept from the second PDF",
    "regenerated": "Regenerated by the PDF writer",
    "failed": "Could not be copied",
    "readonly": "Read-only (inspected, intentionally not modified)",
}

NAME_RE = re.compile(r"^/[^\s/\[\]()<>{}%]*$")
PERMISSIONS = ["accessibility", "extract", "modify_annotation", "modify_assembly", "modify_form",
               "modify_other", "print_lowres", "print_highres"]


class PlanError(ValueError):
    pass


# ----------------------------------------------------------------------------- options


@dataclass
class Options:
    annotations: str = "keep"          # keep | replace | merge
    struct_tree: str = "keep"          # keep | copy
    id_mode: str = "exact"             # exact | first
    header_mode: str = "match"         # match | writer (header line + binary marker bytes)
    numbering: str = "preserve"        # preserve (original's object numbers) | writer (qpdf renumbers)
    propagate_xmp: bool = True
    version: str = ""                  # header version to write ("" = automatic)
    linearize: bool = False
    object_streams: str = "match"      # match | generate | disable | preserve
    compress: bool = False
    encryption: str = "none"           # none | original | second
    enc_user: str = ""
    enc_owner: str = ""
    enc_allow: dict = field(default_factory=lambda: {p: True for p in PERMISSIONS})
    enc_R: int = 6
    enc_aes: bool = True
    enc_metadata: bool = True

    @classmethod
    def from_dict(cls, d: dict) -> "Options":
        o = cls()
        for k, v in d.items():
            if hasattr(o, k):
                setattr(o, k, v)
        return o

    def to_dict(self) -> dict:
        return asdict(self)


def default_options(orig: dict, second: dict, orig_password: str = "") -> Options:
    """Defaults that reproduce the original as closely as possible."""
    s = orig["summary"]
    by_id = {e["id"]: e for e in orig["entries"]}
    # Keeping the original's object numbers takes precedence over linearization (only qpdf's
    # writer can linearize, and it renumbers every object).
    o = Options(version=s.get("header_version") or s["version"], linearize=False)
    if s["encrypted"]:
        o.encryption = "original"
        o.enc_user = orig_password
        try:
            o.enc_R = int(by_id["structure:enc:Security handler revision (R)"]["display"])
        except (KeyError, ValueError):
            pass
        method = by_id.get("structure:enc:Stream method", {}).get("display", "")
        o.enc_aes = method.startswith("aes")
        allowed = by_id.get("structure:enc:allow", {}).get("display", "")
        o.enc_allow = {p: p in allowed.split(", ") for p in PERMISSIONS}
        meta = by_id.get("structure:enc:meta")
        o.enc_metadata = not (meta and meta["present"] and meta["display"] == "No")
    return o


# ----------------------------------------------------------------------------- plan validation


def validate_value(row: dict, value: str) -> str | None:
    """Return an error message if ``value`` is not acceptable for ``row``."""
    kind = row["kind"]
    if kind == "date":
        if value.strip() and not pdfobj.is_pdf_date(value):
            return "Not a PDF date. Use D:YYYYMMDDHHmmSSOHH'mm' (e.g. D:20240131120000+01'00')."
    elif kind == "name":
        if not NAME_RE.match(value.strip()):
            return "A PDF name starts with '/' and contains no spaces or delimiters."
    elif kind == "number":
        try:
            float(value)
        except ValueError:
            return "Not a number."
    elif kind == "bool":
        if value not in ("true", "false"):
            return "Choose true or false."
    elif kind == "binary":
        if not pdfobj.HEX_RE.match(value) or len("".join(value.split())) % 2:
            return "Hexadecimal digits (an even number of them) expected."
    elif kind == "object":
        try:
            parsed = json.loads(value)
            pdfobj.from_json(parsed, lambda n, g: None)
        except json.JSONDecodeError as e:
            return f"Invalid JSON: {e}"
        except pdfobj.DecodeError as e:
            return str(e)
    elif kind == "xml":
        if value.strip():
            return xmp.check_wellformed(value)
    return None


def build_plan(rows: list[dict], submitted: dict[str, dict]) -> tuple[dict[str, dict], dict[str, str]]:
    """Turn submitted form values into a plan, validating custom values.

    ``submitted`` maps row ids to ``{"action": ..., "value": ...}`` for rows
    the user touched; untouched rows use their default action at copy time.
    A "custom" value equal to the original's is treated as a plain copy.
    """
    by_id = {r["id"]: r for r in rows}
    plan: dict[str, dict] = {}
    errors: dict[str, str] = {}
    for id, sub in submitted.items():
        row = by_id.get(id)
        if row is None:
            continue
        action = sub.get("action") or row["default"]
        value = sub.get("value")
        if action not in row["actions"]:
            if action == row["default"]:
                continue
            errors[id] = f"'{action}' is not possible for this property."
            continue
        if action == CUSTOM:
            value = "" if value is None else value.replace("\r\n", "\n")
            if row["kind"] not in ("xml",) and value == (row["o"]["edit"] or "") and row["o"]["present"]:
                plan[id] = {"action": COPY, "explicit": True}
                continue
            if row["kind"] == "xml" and value == (row["o"]["edit"] or ""):
                plan[id] = {"action": COPY, "explicit": True}
                continue
            err = validate_value(row, value)
            if err:
                errors[id] = err
                continue
            plan[id] = {"action": CUSTOM, "value": value, "explicit": True}
        else:
            plan[id] = {"action": action, "explicit": True}
    return plan, errors


# ----------------------------------------------------------------------------- the job


class Job:
    def __init__(self, src: Pdf, dst: Pdf, rows: list[dict], plan: dict, opts: Options, max_pages: int) -> None:
        self.src, self.dst, self.rows, self.plan, self.opts = src, dst, rows, plan, opts
        self.by_id = {r["id"]: r for r in rows}
        self.items: list[dict] = []
        self.notes: list[str] = []
        self.tr = Transplanter(src, dst)
        self.max_pages = max_pages
        self.done: set[str] = set()
        self.propagated: set[str] = set()

    # -- reporting -------------------------------------------------------------------------

    def report(self, row: dict | str, outcome: str, message: str = "", *, partial: bool = False) -> None:
        if isinstance(row, str):
            row = self.by_id.get(row) or {"id": row, "label": row, "path": ["Output"]}
        self.done.add(row["id"])
        self.items.append({"id": row["id"], "label": row["label"], "section": row["path"][0],
                           "group": row["path"][1] if len(row["path"]) > 1 else "", "outcome": outcome,
                           "message": message, "partial": partial})

    def action(self, row: dict) -> str:
        p = self.plan.get(row["id"])
        return p["action"] if p else row["default"]

    def explicit(self, row: dict) -> bool:
        return bool(self.plan.get(row["id"], {}).get("explicit"))

    def value(self, row: dict) -> str:
        return self.plan[row["id"]]["value"]

    def rows_with(self, prefix: str) -> list[dict]:
        return [r for r in self.rows if r["id"].startswith(prefix)]

    # -- value construction ----------------------------------------------------------------

    def resolve_ref(self, num: int, gen: int) -> Any:
        try:
            return self.tr.copy(self.src.get_object((num, gen)))
        except Exception as e:
            raise PlanError(f"reference {num} {gen} R does not exist in the original ({e})") from e

    def custom_object(self, row: dict, like: Any = None) -> Any:
        kind, value = row["kind"], self.value(row)
        if kind == "text":
            return pdfobj.encode_text(value, bytes(like) if is_obj(like, String) else None)
        if kind == "date":
            return String(value.strip().encode("ascii"))
        if kind == "name":
            return Name(value.strip())
        if kind == "number":
            return int(value) if re.fullmatch(r"[+-]?\d+", value.strip()) else pdfobj.Decimal(value.strip())
        if kind == "bool":
            return value == "true"
        if kind == "binary":
            return String(bytes.fromhex("".join(value.split())))
        if kind == "object":
            return pdfobj.from_json(json.loads(value), self.resolve_ref)
        raise PlanError(f"values of kind {kind!r} cannot be set here")

    def outcome_for_copy(self, row: dict) -> str:
        return "copied" if row["cls"] == DIRECT else "reconstructed"

    # -- generic dictionary key ------------------------------------------------------------

    def apply_key(self, row: dict, container: Any, key: str, src_value: Any, *, ensure: Any = None) -> None:
        """Apply a row's action to ``container[key]``. ``ensure`` creates the container if needed."""
        action = self.action(row)
        o_present, s_present = row["o"]["present"], row["s"]["present"]
        if action == KEEP:
            if o_present or s_present:
                self.report(row, "kept", "" if row["status"] == "same" else "Differs from the original by choice.")
            return
        if container is None and action in (COPY, CUSTOM) and (src_value is not None or action == CUSTOM):
            container = ensure() if ensure else None
        if action == REMOVE or (action == COPY and src_value is None):
            if container is not None and key in container:
                del container[key]
                self.report(row, "removed", "Absent in the original." if action == COPY else "Removed as chosen.")
            return
        if container is None:
            self.report(row, "failed", "No place to write this value in the output.")
            return
        if action == COPY:
            self.tr.last_dropped = set()
            new = self.tr.copy(src_value)
            if new is None:
                self.report(row, "failed", "It refers only to pages that do not exist in the second PDF.")
                return
            container[key] = new
            if self.tr.last_dropped:
                pages = ", ".join(map(str, sorted(self.tr.last_dropped)))
                self.report(row, "reconstructed", f"Copied, but references to original page(s) {pages} became "
                            "null: the second PDF has no such page.", partial=True)
            else:
                self.report(row, self.outcome_for_copy(row))
            return
        try:
            container[key] = self.custom_object(row, src_value)
            self.report(row, "overridden", f"Set to {row['kind']} value from the edit screen.")
        except (PlanError, pdfobj.DecodeError, ValueError) as e:
            self.report(row, "failed", str(e))

    # -- sections --------------------------------------------------------------------------

    def run(self) -> None:
        self.do_annotations_mode()
        self.do_catalog()
        self.do_struct_tree()
        self.do_pages()
        self.do_annotation_fields()
        self.do_image_metadata()
        self.do_info()
        self.do_xmp()
        self.do_trailer()
        if self.tr.dropped_pages:
            self.notes.append("References to original page(s) " + ", ".join(map(str, sorted(self.tr.dropped_pages)))
                              + " were set to null because the second PDF has no such page.")
        if self.tr.stripped_signatures:
            self.notes.append(f"{self.tr.stripped_signatures} signature value(s) were removed from copied "
                              "signature fields; the fields are copied unsigned.")
        for r in self.rows:
            if r["id"] in self.done:
                continue
            if r["cls"] == REGENERATE and (r["o"]["present"] or r["s"]["present"]):
                self.report(r, "regenerated", r["note"])
            elif r["cls"] == READONLY and r["o"]["present"]:
                self.report(r, "readonly")
            elif r["copy_status"] == "unable_copy" and r["o"]["present"]:
                self.report(r, "failed", r.get("copy_reason") or r["note"])
            elif r["cls"] == UNREPRODUCIBLE and r["o"]["present"] and not r["actions"] \
                    and r["id"].startswith(("catalog:", "page:", "annot:", "trailer:")):
                self.report(r, "failed", r["note"])

    def do_annotations_mode(self) -> None:
        mode = self.opts.annotations
        src, dst = self.src, self.dst
        n = min(len(src.pages), len(dst.pages))
        acro_row = self.by_id.get("catalog:/AcroForm") or {"id": "catalog:/AcroForm", "label": "/AcroForm",
                                                           "path": ["Catalog", "Catalog entries"]}
        if mode == "keep":
            for i in range(n):
                sa = src.pages[i].obj.get("/Annots") or []
                da = dst.pages[i].obj.get("/Annots") or []
                for j, a in enumerate(sa):
                    if j < len(da) and is_obj(a, Dictionary) and is_obj(da[j], Dictionary) and a.is_indirect \
                            and a.get("/Subtype") == da[j].get("/Subtype"):
                        self.tr.remap[a.objgen] = da[j]
            if acro_row.get("o", {}).get("present") or acro_row.get("s", {}).get("present"):
                self.report(acro_row, "kept", "Annotations & forms option: keep the second PDF's.")
            return
        copied = 0
        for i in range(len(src.pages)):
            sa = src.pages[i].obj.get("/Annots")
            if not is_obj(sa, Array) or not len(sa):
                continue
            if i >= n:
                self.notes.append(f"{len(sa)} annotation(s) on original page {i + 1} were not copied: the second "
                                  "PDF has no such page.")
                continue
            new = [self.tr.copy(a) for a in sa]
            new = [a for a in new if a is not None]
            page = dst.pages[i].obj
            if mode == "replace" or not is_obj(page.get("/Annots"), Array):
                page.Annots = dst.make_indirect(Array(new)) if new else Array()
            else:
                for a in new:
                    page.Annots.append(a)
            copied += len(new)
        src_acro = src.Root.get("/AcroForm")
        if mode == "replace":
            if src_acro is not None:
                stripped = self.tr.stripped_signatures
                self.tr.last_dropped = set()
                dst.Root.AcroForm = self.tr.copy(src_acro)
                partial = bool(self.tr.stripped_signatures or self.tr.last_dropped or stripped)
                self.report(acro_row, "reconstructed", "Replaced with the original's form. Signature fields are "
                            "copied unsigned; fields on pages missing from the second PDF are detached."
                            if partial else "Replaced with the original's form.", partial=partial)
            elif "/AcroForm" in dst.Root:
                del dst.Root["/AcroForm"]
                self.report(acro_row, "removed", "The original has no interactive form.")
        elif src_acro is not None:
            dst_acro = dst.Root.get("/AcroForm")
            if not is_obj(dst_acro, Dictionary):
                dst.Root.AcroForm = self.tr.copy(src_acro)
            else:
                fields = dst_acro.get("/Fields")
                if not is_obj(fields, Array):
                    dst_acro.Fields = fields = Array()
                for f in src_acro.get("/Fields", []) or []:
                    c = self.tr.copy(f)
                    if c is not None:
                        fields.append(c)
            self.report(acro_row, "reconstructed", "Original's form fields added to the second PDF's form.")
        self.notes.append(f"Annotations: {copied} annotation(s) "
                          f"{'replaced the second PDF’s' if mode == 'replace' else 'added from the original'}; "
                          "popups and replies remain linked.")

    def do_catalog(self) -> None:
        src_root, dst = self.src.Root, self.dst
        for row in self.rows_with("catalog:"):
            if not row["actions"]:
                continue
            key = row["id"][len("catalog:"):]
            parts = ["/" + p for p in key.split("/") if p]
            if len(parts) == 1:
                self.apply_key(row, dst.Root, parts[0], src_root.get(parts[0]))
            else:
                parent, sub = parts[0], parts[1]
                sp = src_root.get(parent)
                src_val = sp.get(sub) if is_obj(sp, Dictionary) else None
                dp = dst.Root.get(parent)

                def ensure(parent: str = parent) -> Any:
                    d = dst.make_indirect(Dictionary()) if parent == "/Names" else Dictionary()
                    dst.Root[parent] = d
                    return dst.Root[parent]

                self.apply_key(row, dp if is_obj(dp, Dictionary) else None, sub, src_val, ensure=ensure)
        for parent in ("/ViewerPreferences", "/MarkInfo", "/Names"):
            d = dst.Root.get(parent)
            if is_obj(d, Dictionary) and not len(d) and parent not in src_root:
                del dst.Root[parent]

    def do_struct_tree(self) -> None:
        row = self.by_id.get("catalog:/StructTreeRoot")
        if row is None:
            return
        tagged = self.by_id.get("structure:tagged")
        if tagged is not None:
            self.report(tagged, "reconstructed" if self.opts.struct_tree == "copy" else "kept",
                        "Follows the 'Structure tree' output option.")
        if self.opts.struct_tree != "copy":
            if row["o"]["present"] or row["s"]["present"]:
                self.report(row, "kept" if row["s"]["present"] else "failed",
                            "Structure tree option: keep the second PDF's tags." if row["s"]["present"] else
                            "Not copied: the original's tags describe different content. Enable "
                            "'Copy structure tree' if the content is the same.")
            return
        src_st = self.src.Root.get("/StructTreeRoot")
        if src_st is None:
            if "/StructTreeRoot" in self.dst.Root:
                del self.dst.Root["/StructTreeRoot"]
            self.report(row, "removed", "The original is not tagged.")
        else:
            self.dst.Root.StructTreeRoot = self.tr.copy(src_st)
            self.report(row, "reconstructed", "Tag tree copied; it is only meaningful if the page content matches.")
        n = min(len(self.src.pages), len(self.dst.pages))
        for i in range(n):
            sp, dp = self.src.pages[i].obj, self.dst.pages[i].obj
            if "/StructParents" in sp:
                dp.StructParents = int(sp.StructParents)
            elif "/StructParents" in dp:
                del dp["/StructParents"]
            r = self.by_id.get(f"page:{i + 1}:/StructParents")
            if r and (r["o"]["present"] or r["s"]["present"]):
                self.report(r, "reconstructed" if "/StructParents" in sp else "removed")

    def do_pages(self) -> None:
        for row in self.rows_with("page:"):
            m = re.match(r"^page:(\d+):(/.+)$", row["id"])
            if not m or not row["actions"]:
                continue
            i, key = int(m.group(1)), m.group(2)
            if i > len(self.dst.pages) or i > self.max_pages:
                continue
            src_val = None
            if i <= len(self.src.pages):
                sp = self.src.pages[i - 1].obj
                src_val = sp.get(key)
                if src_val is None and key in ("/MediaBox", "/CropBox", "/Rotate"):
                    src_val = _inherited(sp, key)
            self.apply_key(row, self.dst.pages[i - 1].obj, key, src_val)

    def do_annotation_fields(self) -> None:
        mode = self.opts.annotations
        for row in self.rows_with("annot:"):
            m = re.match(r"^annot:(\d+):(\d+):(/.+)$", row["id"])
            if not m:
                continue
            if mode != "keep":
                if row["cls"] in (DIRECT, RECONSTRUCT) and row["o"]["present"]:
                    if int(m.group(1)) > len(self.dst.pages):
                        self.report(row, "failed", "The annotation's page does not exist in the second PDF.")
                    else:
                        self.report(row, "reconstructed", "Copied as part of the whole annotation.")
                continue
            if not row["actions"]:
                continue
            p, j, key = int(m.group(1)), int(m.group(2)), m.group(3)
            sa = self.src.pages[p - 1].obj.get("/Annots")
            da = self.dst.pages[p - 1].obj.get("/Annots")
            src_val = sa[j - 1].get(key)
            if key in ("/Popup", "/IRT") and self.action(row) == COPY and src_val is not None \
                    and not (src_val.is_indirect and src_val.objgen in self.tr.remap):
                self.report(row, "failed", "The annotation it points to has no counterpart in the second PDF; "
                            "linking to a copy outside the page would create an orphan annotation.")
                continue
            self.apply_key(row, da[j - 1], key, src_val)

    def do_image_metadata(self) -> None:
        rows = [r for r in self.rows_with("image:") if r["id"].endswith(":/Metadata") and r["actions"]]
        if not rows:
            return
        s_imgs = [f.obj for f in resources.collect(self.src, self.max_pages).images.values()]
        d_imgs = [f.obj for f in resources.collect(self.dst, self.max_pages).images.values()]
        for row in rows:
            n = int(row["id"].split(":")[1])
            if n > len(s_imgs) or n > len(d_imgs):
                continue
            self.apply_key(row, d_imgs[n - 1], "/Metadata", s_imgs[n - 1].get("/Metadata"))

    def do_info(self) -> None:
        src_info = self.src.trailer.get("/Info")
        dst_info = self.dst.trailer.get("/Info")
        src_info = src_info if is_obj(src_info, Dictionary) else None
        dst_info = dst_info if is_obj(dst_info, Dictionary) else None
        new = Dictionary()
        for row in self.rows_with("info:"):
            key = row["id"][len("info:"):]
            action = self.action(row)
            ov = src_info.get(key) if src_info is not None else None
            sv = dst_info.get(key) if dst_info is not None else None
            if action == COPY:
                if ov is not None:
                    new[key] = self.tr.copy(ov)
                    self.report(row, "copied")
                elif sv is not None:
                    self.report(row, "removed", "Absent in the original.")
            elif action == KEEP:
                if sv is not None:
                    new[key] = sv
                if ov is not None or sv is not None:
                    self.report(row, "kept")
            elif action == REMOVE:
                if ov is not None or sv is not None:
                    self.report(row, "removed", "Removed as chosen.")
            elif action == CUSTOM:
                try:
                    new[key] = self.custom_object(row, ov)
                    self.report(row, "overridden")
                except (PlanError, ValueError) as e:
                    self.report(row, "failed", str(e))
        for key, value in self.plan.get("__add_info__", {}).get("items", []):
            new[key] = pdfobj.encode_text(value)
            self.report({"id": f"info:{key}", "label": key[1:], "path": ["Document Info", "Added keys"]},
                        "overridden", "Key added on the edit screen.")
        if len(new) == 0 and src_info is None:
            if "/Info" in self.dst.trailer:
                del self.dst.trailer["/Info"]
        else:
            self.dst.trailer.Info = self.dst.make_indirect(new)

    def do_xmp(self) -> None:
        row = self.by_id.get("xmp:packet")
        if row is None:
            return
        src_md, dst_md = self.src.Root.get("/Metadata"), self.dst.Root.get("/Metadata")
        orig_bytes = src_md.read_bytes() if is_obj(src_md, Stream) else None
        second_bytes = dst_md.read_bytes() if is_obj(dst_md, Stream) else None
        action = self.action(row)
        base: bytes | None
        if action == COPY:
            base, base_from = orig_bytes, "original"
        elif action == KEEP:
            base, base_from = second_bytes, "second"
        elif action == REMOVE:
            base, base_from = None, "none"
        else:
            base, base_from = self.value(row).encode("utf-8"), "custom"
        edits = []
        for prow in self.rows_with("xmp:p:"):
            if not self.explicit(prow) or prow["xmp"] is None:
                continue
            edits.append(self._xmp_edit(prow))
        if self.opts.propagate_xmp:
            edits += self._propagated_edits()
        edits = [e for e in edits if e is not None]
        if edits and base is None:
            base = xmp.minimal_packet()
        final = base
        if edits:
            try:
                final = xmp.apply_edits(base, edits)  # type: ignore[arg-type]
            except Exception as e:
                self.report(row, "failed", f"Could not apply XMP property edits: {e}")
                edits = []
        if final is None:
            if "/Metadata" in self.dst.Root:
                del self.dst.Root["/Metadata"]
            if row["o"]["present"] or row["s"]["present"]:
                self.report(row, "removed", "The original has no XMP." if action == COPY else "Removed as chosen.")
        elif final == orig_bytes and is_obj(src_md, Stream):
            self.dst.Root.Metadata = self.tr.copy(src_md)
            self.report(row, "copied", "Byte-for-byte identical packet.")
        else:
            self.dst.Root.Metadata = self.dst.make_stream(final, Type=Name.Metadata, Subtype=Name.XML)
            if base_from == "second" and not edits:
                self.report(row, "kept")
            elif base_from == "custom":
                self.report(row, "overridden", "Packet replaced with the edited XML" +
                            (f" plus {len(edits)} property edit(s)." if edits else "."))
            else:
                self.report(row, "overridden" if edits else "reconstructed",
                            f"Packet from the {base_from} PDF re-serialized with {len(edits)} property edit(s).")
        for prow in self.rows_with("xmp:p:"):
            if prow["id"] in self.done or not (prow["o"]["present"] or prow["s"]["present"]):
                continue
            a = self.action(prow)
            if prow["id"] in self.propagated:
                self.report(prow, "overridden", "Set from the matching Document Info override.")
            elif self.explicit(prow):
                self.report(prow, {"copy": "reconstructed", "keep": "kept", "remove": "removed",
                                   "custom": "overridden"}[a])
            elif final is not None and final == orig_bytes:
                self.report(prow, "copied", "Part of the byte-identical packet.") if prow["o"]["present"] else \
                    self.report(prow, "removed", "Absent in the original's packet.")
            else:
                self.report(prow, {"original": "reconstructed", "second": "kept", "custom": "overridden",
                                   "none": "removed"}[base_from], "Follows the packet-level choice.")

    def _xmp_edit(self, prow: dict) -> dict | None:
        info = prow["xmp"]
        a = self.action(prow)
        base = {"uri": info["uri"], "local": info["local"], "prefix": info["prefix"], "vtype": info["vtype"]}
        if a in (COPY, KEEP):
            side = prow["o"] if a == COPY else prow["s"]
            xml = self._side_xml(prow, "o" if a == COPY else "s")
            return {**base, "op": "xml", "xml": xml} if side["present"] and xml else {**base, "op": "remove"}
        if a == REMOVE:
            return {**base, "op": "remove"}
        value = self.value(prow)
        if prow["kind"] == "xmp-list":
            return {**base, "op": "list", "value": [v for v in value.split("\n") if v.strip()]}
        return {**base, "op": "text", "value": value}

    def _side_xml(self, prow: dict, side: str) -> str | None:
        return prow.get("xml_" + side)

    def _propagated_edits(self) -> list[dict]:
        out = []
        for key, (prefix, local) in xmp.INFO_TO_XMP.items():
            irow = self.by_id.get(f"info:{key}")
            if irow is None or self.action(irow) != CUSTOM:
                continue
            uri = xmp.NAMESPACES[prefix][0]
            prow = self.by_id.get(xmp.prop_id(uri, local))
            if prow is not None and self.explicit(prow):
                continue
            value = self.value(irow)
            vtype = dict(xmp.SCHEMA_PROPS[prefix]).get(local, "T")
            base = {"uri": uri, "local": local, "prefix": prefix, "vtype": vtype}
            if key in ("/CreationDate", "/ModDate"):
                value = pdfobj.pdf_date_to_iso(value) or value
            if key == "/Trapped":
                value = value.lstrip("/")
            self.propagated.add(xmp.prop_id(uri, local))
            if vtype == "S":
                out.append({**base, "op": "list", "value": [value]})
            else:
                out.append({**base, "op": "text", "value": value})
            self.notes.append(f"Info {key} override also written to XMP {prefix}:{local}.")
        return out

    def do_trailer(self) -> None:
        for row in self.rows_with("trailer:"):
            key = row["id"][len("trailer:"):]
            if key == "/ID" or not row["actions"]:
                continue
            self.apply_key(row, self.dst.trailer, key, self.src.trailer.get(key))
        row = self.by_id.get("trailer:/ID")
        if row is None:
            return
        action = self.action(row)
        sid = self.src.trailer.get("/ID")
        if action == COPY and is_obj(sid, Array):
            self.dst.trailer.ID = self.tr.copy(sid)
        elif action == COPY:
            if "/ID" in self.dst.trailer:
                del self.dst.trailer["/ID"]
            self.report(row, "regenerated", "The original has no /ID, but a PDF writer always writes one "
                        "(required for PDF 2.0 and encrypted files); a new identifier was generated.")
        elif action == CUSTOM:
            try:
                self.dst.trailer.ID = self.custom_object(row)
            except (PlanError, ValueError) as e:
                self.report(row, "failed", str(e))
                return
        elif action == REMOVE and "/ID" in self.dst.trailer:
            del self.dst.trailer["/ID"]
        # The outcome is reported after saving, when it is known whether the ID survived.


def _inherited(page: Any, key: str) -> Any:
    node, hops = page.get("/Parent"), 0
    while node is not None and hops < 50:
        if key in node:
            return node[key]
        node, hops = node.get("/Parent"), hops + 1
    return None


# ----------------------------------------------------------------------------- save


def _encryption(opts: Options, report: list[str]) -> Any:
    if opts.encryption == "second":
        return True
    if opts.encryption != "original":
        return False
    owner = opts.enc_owner
    if not owner:
        owner = secrets.token_urlsafe(16)
        report.append(f"No owner password was given; a random one was generated: {owner}")
    allow = pikepdf.Permissions(**{p: bool(opts.enc_allow.get(p, True)) for p in PERMISSIONS})
    R = int(opts.enc_R)
    kw: dict[str, Any] = {"owner": owner, "user": opts.enc_user, "R": R, "allow": allow}
    # AES is optional at R4, mandatory from R5, unavailable (RC4 only) below R4.
    kw["aes"] = bool(opts.enc_aes) if R == 4 else R >= 5
    # pikepdf accepts the /EncryptMetadata choice only together with AES.
    kw["metadata"] = bool(opts.enc_metadata) if kw["aes"] else False
    if opts.enc_metadata is False and not kw["aes"]:
        report.append("Leaving metadata unencrypted requires AES; the metadata is encrypted with RC4.")
    return pikepdf.Encryption(**kw)


def _patch_id(path: Path, want: list[bytes]) -> str:
    """Make the output's /ID equal ``want`` by same-length byte substitution."""
    with Pdf.open(path) as pdf:
        got = pdf.trailer.get("/ID")
        got_b = [bytes(x) for x in got] if is_obj(got, Array) else []
    if got_b == want:
        return "exact"
    if len(got_b) != 2 or len(want) != 2 or [len(x) for x in got_b] != [len(x) for x in want]:
        return "length"
    data = path.read_bytes()
    for g, w in zip(got_b, want):
        if g == w:
            continue
        old, new = b"<" + g.hex().encode() + b">", b"<" + w.hex().encode() + b">"
        if data.count(old) == 0 or data.count(old) > 4:
            return "not-found"
        data = data.replace(old, new)
    tmp = path.with_suffix(".idpatch")
    tmp.write_bytes(data)
    try:
        with Pdf.open(tmp) as pdf:
            ok = [bytes(x) for x in pdf.trailer.ID] == want and not pdf.get_warnings()
    except Exception:
        ok = False
    if not ok:
        tmp.unlink(missing_ok=True)
        return "verify"
    tmp.replace(path)
    return "exact"


def _reproduce_header(original: Path, output: Path, password: str) -> tuple[str | None, str]:
    """Give the output the original's header line and binary-marker bytes."""
    with open(original, "rb") as f:
        head = f.read(4096)
    start = head.find(b"%PDF-")
    if start == -1:
        return None, ""
    block, _, _ = rawfile.header_block(head, start)
    with open(output, "rb") as f:
        m = re.match(rb"%PDF-(\d+\.\d+)", f.read(16))
    version = m.group(1).decode() if m else "1.7"
    desired = headerfix.desired_block(block, version)
    status, message = headerfix.rewrite_header(output, desired, password)
    if desired != block and status != "failed":
        message += f" The version was written as {version} (see the PDF version option and notes)."
    if start and status != "failed":
        message += f" The {start} byte(s) before the original's %PDF header were not reproduced."
    return status, message


def _write_preserving_numbers(src: Pdf, dst: Pdf, job: Job, original: Path, output: Path, opts: Options,
                              enc: Any, version: str, second_password: str, notes: list[str]) -> dict | None:
    """Write ``output`` with the original's object numbers; None (with a note) if that fails."""
    tr = job.tr
    pairs: list[tuple[Any, Any]] = [(src.Root, dst.Root), (src.trailer.get("/Info"), dst.trailer.get("/Info")),
                                    (src.Root.get("/Pages"), dst.Root.get("/Pages")),
                                    (src.Root.get("/Metadata"), dst.Root.get("/Metadata"))]
    pairs += [(src.pages[i].obj, dst.pages[i].obj) for i in range(min(len(src.pages), len(dst.pages)))]
    pairs += [(src.get_object(og), d) for og, d in tr.memo.items()]
    pairs += [(src.get_object(og), d) for og, d in tr.remap.items() if is_obj(d, pikepdf.Object)]
    membership = numbering.objstm_membership(src)
    xref_nums = numbering.xref_streams(src)
    src_enc = src.trailer.get("/Encrypt")
    reserve = set(membership.values()) | set(xref_nums)
    if is_obj(src_enc, pikepdf.Object) and src_enc.is_indirect:
        reserve.add(src_enc.objgen[0])

    password = _output_password(opts, second_password)
    setup = None
    write_version = version or dst.pdf_version
    try:
        if enc is not False:
            setup = pdfwriter.prepare_encryption(dst, enc, password)
            if setup.encryptor.R >= 5 and write_version < "1.7":
                notes.append(f"PDF version raised from {write_version} to 1.7: AES-256 encryption requires it.")
                write_version = "1.7"
        nb = numbering.build_map(src, dst, pairs, reserve=reserve)
    except Exception as e:  # pragma: no cover - defensive
        notes.append(f"Object numbers could not be kept ({e}); qpdf renumbered them.")
        return None

    # Object streams: same membership as the original; objects new to the output join an extra stream.
    mode = opts.object_streams
    replicate = mode != "disable" and bool(membership)
    layout = pdfwriter.Layout(xref_stream=bool(xref_nums), xref_num=xref_nums[-1] if xref_nums else None,
                              size_min=nb.src_size, compress=bool(opts.compress),
                              encrypt_num=src_enc.objgen[0] if is_obj(src_enc, pikepdf.Object)
                              and src_enc.is_indirect else None)
    taken = {n for n, _ in nb.map.values()} | reserve
    extra_k = max(taken | {nb.src_max}) + 1
    for og, (n, g) in nb.map.items():
        if replicate and nb.kind[og] in ("counterpart", "structural") and n in membership:
            layout.objstm_of[n] = membership[n]
        elif (replicate or mode == "generate") and g == 0:
            layout.objstm_of[n] = extra_k
    if layout.encrypt_num in taken - reserve:
        layout.encrypt_num = None

    ident = [bytes(x) for x in dst.trailer.ID] if is_obj(dst.trailer.get("/ID"), Array) else None
    if setup is not None and (ident is None or len(ident) != 2 or ident[0] != setup.id[0]):
        ident = setup.id  # the encryption key was derived from this /ID
    with open(original, "rb") as f:
        head = f.read(4096)
    start = head.find(b"%PDF-")
    orig_header = rawfile.header_block(head, start)[0] if start != -1 else b"%PDF-1.7\n"
    header = (headerfix.desired_block(orig_header, write_version) if opts.header_mode == "match"
              else b"%PDF-" + write_version.encode() + b"\n%\xbf\xf7\xa2\xfe\n")

    tmp = output.with_suffix(".numbered.tmp")
    try:
        written = pdfwriter.write(dst, nb, tmp, header, layout, ident=ident, encryption=setup)
        problem = pdfwriter.verify(dst, nb, tmp, password, written)
    except Exception as e:
        problem = f"{type(e).__name__}: {e}"
    if problem:
        tmp.unlink(missing_ok=True)
        notes.append(f"Object numbers could not be kept: the file written with them did not verify "
                     f"({problem}). qpdf wrote the output and renumbered the objects.")
        return None
    tmp.replace(output)

    stats = nb.stats()
    notes.append(f"Object numbers: {stats['counterpart']} object(s) kept the original's number, "
                 f"{stats['structural']} took the number of the original object in the same place, "
                 f"{stats['reused']} reused numbers of original objects not in the output, and {stats['new']} "
                 f"got new numbers above the original's highest ({nb.src_max}).")
    reports: list[tuple[str, str, str, bool]] = []

    def same_number(row_id: str, s_obj: Any, d_obj: Any, label: str) -> None:
        if not (is_obj(s_obj, pikepdf.Object) and s_obj.is_indirect):
            return
        got = nb.map.get(d_obj.objgen) if is_obj(d_obj, pikepdf.Object) and d_obj.is_indirect else None
        if got == s_obj.objgen:
            reports.append((row_id, "copied", f"{label} is object {got[0]} {got[1]}, as in the original.", False))
        else:
            reports.append((row_id, "failed", f"{label} could not keep number {s_obj.objgen[0]} "
                            f"{s_obj.objgen[1]}" + (" (not present in the output)." if got is None else
                                                    f"; it is {got[0]} {got[1]}."), False))

    same_number("structure:objnum:root", src.Root, dst.Root, "The catalog")
    same_number("structure:objnum:info", src.trailer.get("/Info"), dst.trailer.get("/Info"), "The Info dictionary")
    same_number("structure:objnum:pages", src.Root.get("/Pages"), dst.Root.get("/Pages"), "The page tree root")
    same_number("structure:objnum:metadata", src.Root.get("/Metadata"), dst.Root.get("/Metadata"), "The XMP stream")
    for i in range(min(len(src.pages), len(dst.pages))):
        same_number(f"page:{i + 1}:objnum", src.pages[i].obj, dst.pages[i].obj, f"Page {i + 1}")
    for i in range(len(dst.pages), len(src.pages)):
        reports.append((f"page:{i + 1}:objnum", "failed", f"The second PDF has no page {i + 1}.", False))
    trailer_size = int(src.trailer.get("/Size", 0) or 0)
    if written.size == trailer_size:
        reports.append(("structure:objnum:size", "copied", f"/Size {written.size}, as in the original.", False))
    else:
        why = ("the original's /Size is smaller than its highest object number + 1, which a valid file "
               "cannot reproduce" if nb.src_size > trailer_size and written.size == nb.src_size else
               "the output contains objects numbered above the original's range")
        reports.append(("structure:objnum:size", "reconstructed", f"/Size is {written.size} (original "
                        f"{trailer_size}): {why}.", True))
    out_members = {n: k for k, ns in written.objstms.items() for n in ns}
    present = {n for n, _ in nb.map.values()}
    common = {n: k for n, k in membership.items() if n in present}
    if membership or out_members:
        exact = out_members == common
        missing = len(membership) - len(common)
        if exact and missing:
            message = (f"Every object present in the output is in the same object stream as in the original; "
                       f"{missing} of the original's compressed objects do not exist in the output.")
        elif exact:
            message = "Same objects in the same object streams as the original."
        elif replicate:
            message = ("The original's object-stream layout was followed; objects that exist only in the output "
                       f"were placed in object stream {extra_k}.")
        else:
            message = f"Object streams: {mode}."
        reports.append(("structure:objnum:objstm", "copied" if exact else "reconstructed", message,
                        not exact or bool(missing)))
    orig_x = f"stream, object {xref_nums[-1]}" if xref_nums else "classic table"
    out_x = f"stream, object {written.xref_num}" if written.xref_num else "classic table"
    reports.append(("structure:objnum:xref", "copied" if orig_x == out_x else "reconstructed",
                    f"Cross-reference data: {out_x}.", orig_x != out_x))
    return {"reports": reports, "id": ident, "header": header, "orig_header": orig_header,
            "version": write_version, "objstm_mode": "same layout as the original" if replicate else mode,
            "xref": out_x}


def _output_password(opts: Options, second_password: str) -> str:
    if opts.encryption == "original":
        return opts.enc_user or opts.enc_owner
    if opts.encryption == "second":
        return second_password
    return ""


def copy_properties(original: Path, original_password: str, second: Path, second_password: str,
                    output: Path, rows: list[dict], plan: dict, opts: Options,
                    *, max_pages: int = 200) -> dict[str, Any]:
    """Write ``output``; return the copy report (items, notes, save details)."""
    notes: list[str] = []
    with Pdf.open(original, password=original_password) as src, \
            Pdf.open(second, password=second_password) as dst:
        job = Job(src, dst, rows, plan, opts, max_pages)
        job.run()
        notes = job.notes
        save_kw: dict[str, Any] = {}
        version = (opts.version or "").strip()
        if version:
            if not re.fullmatch(r"\d\.\d", version):
                raise PlanError(f"Invalid PDF version {version!r}")
            save_kw["force_version"] = version
        osm = opts.object_streams
        if osm == "match":
            orig_objstm = job.by_id.get("structure:object_streams", {}).get("o", {}).get("display", "No")
            osm = "generate" if orig_objstm.startswith("Yes") else "disable"
        save_kw["object_stream_mode"] = {"generate": pikepdf.ObjectStreamMode.generate,
                                         "disable": pikepdf.ObjectStreamMode.disable,
                                         "preserve": pikepdf.ObjectStreamMode.preserve}[osm]
        save_kw["compress_streams"] = bool(opts.compress)
        save_kw["linearize"] = bool(opts.linearize)
        enc = _encryption(opts, notes)
        save_kw["encryption"] = enc
        if isinstance(enc, pikepdf.Encryption) and enc.R >= 5 and version and version < "2.0":
            # AES-256 needs PDF 1.7 with Adobe extension level 3 (R5) or 8 (R6); without it qpdf
            # would silently drop the encryption to honour the forced version.
            level = 8 if enc.R == 6 else 3
            save_kw["force_version"] = ("1.7", level)
            if version != "1.7":
                notes.append(f"PDF version raised from {version} to 1.7 (extension level {level}): AES-256 "
                             f"encryption (R{enc.R}) requires it.")
        want_id = None
        if is_obj(dst.trailer.get("/ID"), Array):
            want_id = [bytes(x) for x in dst.trailer.ID]
        md = dst.Root.get("/Metadata")
        want_xmp = md.read_bytes() if is_obj(md, Stream) else None
        orig_linearized = job.by_id.get("structure:linearized", {}).get("o", {}).get("display") == "Yes"
        preserved = None
        if opts.numbering == "preserve":
            if opts.linearize:
                notes.append("Linearization was requested, so qpdf wrote the file and renumbered the objects.")
            else:
                preserved = _write_preserving_numbers(src, dst, job, original, output, opts, enc, version,
                                                      second_password, notes)
        if preserved is None:
            # fix_metadata_version=False: pikepdf would otherwise re-serialize the XMP packet to update
            # pdf:PDFVersion. The packet written is the one the user approved (verified below).
            dst.save(output, fix_metadata_version=False, **save_kw)
        else:
            save_kw = {"writer": "dittopdf (original object numbers)", "object_streams": preserved["objstm_mode"],
                       "xref": preserved["xref"], "header_version": preserved["version"]}

    with Pdf.open(output, password=_output_password(opts, second_password)) as out:
        md = out.Root.get("/Metadata")
        got_xmp = md.read_bytes() if is_obj(md, Stream) else None
        if got_xmp != want_xmp and "xmp:packet" in job.by_id:
            job.report(job.by_id["xmp:packet"], "failed",
                       "The PDF writer altered the XMP packet while saving; the output's packet differs from "
                       "the one prepared.")
        enc_ok = out.is_encrypted == (opts.encryption != "none")
        structure = {
            "structure:header_version": f"Header written as %PDF-{out.pdf_version}.",
            "structure:linearized": "Linearized." if out.is_linearized else "Not linearized.",
            "structure:object_streams": f"Object streams: {osm}.",
            "structure:encrypted": {"none": "Written unencrypted.", "original": "Encrypted with the original's "
                                    "method and permissions and the passwords you gave.",
                                    "second": "Second PDF's encryption kept."}[opts.encryption],
        }
    if preserved is not None:
        structure["structure:object_streams"] = f"Object streams: {preserved['objstm_mode']}."
    for id, msg in structure.items():
        if id in job.by_id:
            if id == "structure:encrypted" and not enc_ok:
                job.report(job.by_id[id], "failed", "The writer did not produce the requested encryption.")
            elif id == "structure:linearized" and orig_linearized and not opts.linearize:
                job.report(job.by_id[id], "reconstructed", "Not linearized: the original's object numbers were "
                           "kept instead (only qpdf's writer can linearize, and it renumbers objects). Choose "
                           "'let the writer renumber' with linearization to get fast web view.", partial=True)
            else:
                job.report(job.by_id[id], "reconstructed", msg)

    for item in (preserved or {}).get("reports", []):
        if item[0] in job.by_id:
            job.report(job.by_id[item[0]], item[1], item[2], partial=item[3])
    if preserved is None:
        reason = ("linearization was requested" if opts.linearize and opts.numbering == "preserve" else
                  "the 'let the writer renumber' option was chosen" if opts.numbering != "preserve" else
                  "see the notes")
        for row in job.rows:
            if (row["id"].startswith("structure:objnum:") or row["id"].endswith(":objnum")) \
                    and (row["o"]["present"] or row["s"]["present"]) and row["id"] not in job.done:
                job.report(row, "regenerated", f"qpdf renumbered the objects because {reason}.")

    # File identifier: qpdf keeps the first element and regenerates the second.
    id_row = job.by_id.get("trailer:/ID")
    if preserved is not None and id_row is not None:
        job.items = [i for i in job.items if i["id"] != "trailer:/ID"]
        if preserved["id"] is None:
            job.report(id_row, "copied", "No /ID written, like the original.")
        elif id_row["o"]["present"] or id_row["s"]["present"] or job.action(id_row) == CUSTOM:
            job.report(id_row, "overridden" if job.action(id_row) == CUSTOM else
                       ("copied" if job.action(id_row) == COPY else "kept"),
                       "Both /ID elements written exactly." + (" (The original has no /ID; one is required for "
                       "encryption.)" if not id_row["o"]["present"] else ""),
                       partial=not id_row["o"]["present"])
    elif id_row is not None and "trailer:/ID" in job.done:
        pass  # already reported (no /ID in the original)
    elif id_row is not None and want_id is not None:
        action = job.action(id_row)
        if enc is False and opts.id_mode == "exact" and len(want_id) == 2:
            result = _patch_id(output, want_id)
        else:
            result = "skipped"
        if result == "exact":
            job.report(id_row, "copied" if action == COPY else "overridden",
                       "Both /ID elements reproduced exactly (same-length substitution after writing).")
        elif result == "skipped":
            why = ("the output is encrypted (the ID is part of the key derivation)" if enc is not False
                   else "the 'first element only' option was chosen")
            job.report(id_row, "reconstructed",
                       f"First /ID element reproduced; the second was regenerated by qpdf because {why}.",
                       partial=True)
        else:
            job.report(id_row, "reconstructed",
                       "First /ID element reproduced; the second could not be substituted safely "
                       f"({result}) and was regenerated by qpdf.", partial=True)
    elif id_row is not None and (id_row["o"]["present"] or id_row["s"]["present"]):
        job.report(id_row, "regenerated", "A new file identifier was generated.")

    header_row = job.by_id.get("structure:binary_marker")
    if preserved is not None:
        if header_row is not None:
            changed = preserved["header"] != preserved["orig_header"]
            job.report(header_row, "copied" if opts.header_mode == "match" else "regenerated",
                       ("Header bytes written exactly." + (f" The version was written as {preserved['version']}."
                                                           if changed else ""))
                       if opts.header_mode == "match" else "The 'writer default' header option was chosen.",
                       partial=changed and opts.header_mode == "match")
    elif opts.header_mode == "match":
        status, message = _reproduce_header(original, output, _output_password(opts, second_password))
        if header_row is not None and status is not None:
            outcome = {"exact": "copied", "rewritten": "copied", "failed": "failed"}[status]
            job.report(header_row, outcome, message, partial="version was written as" in message)
    elif header_row is not None:
        job.report(header_row, "regenerated", "The 'writer default' header option was chosen.")

    return {"items": job.items, "notes": notes,
            "save": {k: (str(v) if not isinstance(v, (bool, str)) else v) for k, v in save_kw.items()
                     if k != "encryption"} | {"encryption": opts.encryption}}
